sudo: required
language: rust
rust:
  - stable

cache: cargo

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      # Install .NET Core SDK for compiling validator
      - dotnet-sdk

script:
  - cargo run --example hello_world
  - dotnet run --project validator/ hello_world.docx

notifications:
  email:
    on_failure: change
    on_success: change
