[package]
name = "docx"
version = "0.1.1"
authors = ["PoiScript <poiscript@gmail.com>"]
exclude = ["validator/*"]
license = "MIT"
repository = "https://github.com/PoiScript/docx-rs"
description = """
A Rust library for generating docx files.
"""

[badges]
travis-ci = { repository = "PoiScript/docx-rs" }

[dependencies]
docx-codegen = { version = "0.1.0", path = "./codegen/" }
log = "0.4.0"
quick-xml = "0.12.0"
zip = "0.2"
