[package]
name = "docx"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
exclude = ["validator/*"]
license = "MIT"
repository = "https://github.com/PoiScript/docx-rs"
description = """
A Rust library for generating docx files.
"""

[badges]
travis-ci = { repository = "PoiScript/docx-rs" }

[dependencies]
codegen = { path = "./codegen/" }
quick-xml = "0.12.0"
zip = "0.2"
