[package]
name = "docx-codegen"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
license = "MIT"
description = "Code generation for docx-rs."

[lib]
name = "docx_codegen"
proc-macro = true

[dependencies]
regex = "1"
quote = "0.6"
proc-macro2 = "0.4"
